export interface Product {
  id: number;
  name: string;
  autogeneratedSlug: string;
  price: number;
  priceInProductList: number;
  defaultDisplayedPrice: number;
  defaultDisplayedPriceFormatted: string;
  imageUrl: string;
  description: string;
  options: Array<{
    type: string;
    name: string;
    choices: Array<{
      text: string;
      priceModifier: number;
      priceModifierType: string;
    }>;
  }>;
  media: {
    images?: Array<{
      id: number;
      isMain: boolean;
      image160pxUrl: string;
      image400pxUrl: string;
      image800pxUrl: string;
      image1500pxUrl: string;
      imageOriginalUrl: string;
    }>;
    videos?: Array<object>;
  };
}

export interface Category {
  id: number;
  orderBy: number;
  name: string;
  nameTranslated: Record<string, string>;
  url: string;
  imageUrl: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  description: string;
  descriptionTranslated: Record<string, string>;
  enabled: boolean;
  isSampleCategory: boolean;
  seoTitle: string;
  seoDescription: string;
  alt: {
    main: string;
  };
  productIds?: number[];
}

