<template>
  <v-card
    :key="category.id"
    class="category-card"
    flat
    @click="goToCategoryPage(category)"
  >
    <div class="category-image-container">
      <v-img
        :src="category.imageUrl"
        alt="Category Image"
        class="category-image"
      />
      <v-card-title class="category-title">
        {{ category.name }}
      </v-card-title>
    </div>
  </v-card>
</template>

<script lang="ts">
import { defineComponent, type PropType } from 'vue';
import { useRouter } from 'vue-router';
import type { Category } from '@/types';

export default defineComponent({
  name: 'CategoryCard',
  props: {
    category: {
      type: Object as PropType<Category>,
      required: true,
    },
  },
  setup() {
    const router = useRouter();
    const goToCategoryPage = (category: Category) => {
      router.push({
        name: 'CategoryPage',
        params: {
          slug: category.autogeneratedSlug,
          id: category.id,
        },
      });
    };

    return {
      goToCategoryPage,
    };
  },
});
</script>

<style scoped>
.category-card {
  cursor: pointer;
  border-radius: 10px;
  overflow: hidden;
  transition: box-shadow 0.3s ease, transform 0.3s ease;
  padding: 10px;
  position: relative;
}

.category-card:hover {
  box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
  transform: translateY(-5px);
}

.category-image-container {
  width: 100%;
  height: 400px;
  position: relative;
}

.category-image {
  object-fit: cover;
  width: 100%;
  height: 100%;
  border-radius: 10px;
}

.category-title {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  color: #fff;
  padding: 10px 20px;
  font-size: 22px;
  font-weight: 700;
  text-align: center;
  border-radius: 5px;
  width: 80%;
}

.category-card {
  background: linear-gradient(135deg, rgba(239, 88, 88, 0.5), rgba(205, 185, 106, 0.7)), no-repeat center center;
  background-size: cover;
  margin: 16px;
}
</style>
