<template>
  <v-card
    :key="product.id"
    class="product-card"
    :link="false"
    @click="goToProductPage(product)"
  >
    <div class="image-container">
      <img
        :src="product.imageUrl"
        alt="Product Image"
        class="product-image"
      >
    </div>
    <v-card-title class="text-h6">
      {{ product.name }}
    </v-card-title>
    <v-card-subtitle
      opacity="0.9"
      class="price-text cyan-darken-1"
    >
      {{ product.defaultDisplayedPriceFormatted }}
    </v-card-subtitle>
    <v-card-actions class="d-flex justify-center">
      <v-btn
        variant="elevated"
        color="primary"
        class="mt-0 mb-0"
        @click.stop="goToProductPage(product)"
      >
        BUY
      </v-btn>
    </v-card-actions>
  </v-card>
</template>

<script lang="ts">
import { defineComponent } from 'vue';
import { useRouter } from 'vue-router';
import type {Category, Product} from '@/types';

export default defineComponent({
  props: {
    product: {
      type: Object as () => Product,
      required: true,
    },
    category: {
      type: Object as () => Category,
      required: false,
      default: null,
    },
  },
  setup(props) {
    const router = useRouter();

    const goToProductPage = (product: Product) => {
      const { category } = props;
      if (category) {
        router.push({
          name: 'ProductPageWithCategory',
          params: {
            category_slug: category.autogeneratedSlug,
            category_id: category.id,
            slug: product.autogeneratedSlug,
            id: product.id,
          },
        });
      } else {
        router.push({
          name: 'ProductPage',
          params: {
            slug: product.autogeneratedSlug,
            id: product.id,
          },
        });
      }
    };

    return { goToProductPage };
  },
});
</script>

<style scoped>
.product-card {
  border: none;
  box-shadow: none;
  padding: 0;
  cursor: pointer;
  transition: none;
}

.image-container {
  position: relative;
  width: 100%;
  height: 560px;
  overflow: hidden;
}

.product-image {
  object-fit: cover;
  width: 100%;
  height: 100%;
  transition: transform 0.3s ease-in-out;
}

.product-card:hover .product-image {
  transform: scale(1.1);
}

.v-card-title,
.v-card-subtitle {
  text-align: center;
  margin: 0;
}

.v-card-actions {
  display: flex;
  justify-content: center;
  padding-top: 8px;
}

.v-btn {
  min-width: 150px;
  font-size: 14px;
  font-weight: bold;
  padding: 10px 20px;
  border-radius: 15px;
}

.price-text {
  font-size: 22px;
  font-weight: bold;
  margin-top: 0;
}
</style>
